#!/usr/bin/env bash
# Configure autologin on TTY1 and auto-start Hyprland via UWSM for a given user.
# Usage: sudo bash setup-autologin-hyprland-uwsm.sh <username>

# Source utility functions
source ../utilities/utils.sh

set -euo pipefail

# Ensure root
require_root

if [[ $# -lt 1 ]]; then
  err "User: $0 <username>"
  exit 1
fi

TARGET_USER="$1"
if ! id "$TARGET_USER" >/dev/null 2>&1; then
  err "The user '$TARGET_USER' don't exist."
  exit 1
fi

USER_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
if [[ -z "$USER_HOME" || ! -d "$USER_HOME" ]]; then
  err "Can't find the HOME folder of $TARGET_USER."
  exit 1
fi

# ---------- sanity checks ----------
is_installed agetty
is_installed uwsm
is_installed Hyprland

# ---------- 1) systemd agetty autologin ----------
info "Configuring auto-login on TTY1 for user $TARGET_USER …"

DROPIN_DIR="/etc/systemd/system/getty@tty1.service.d"
DROPIN_FILE="$DROPIN_DIR/override.conf"

mkdir -p "$DROPIN_DIR"

cat >"$DROPIN_FILE" <<EOF
# Generated by setup-autologin.sh
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin ${TARGET_USER} --noclear %I \$TERM
Type=simple
EOF

ok "Drop-in writen: $DROPIN_FILE"

# Activate and reload the system
systemctl daemon-reload
systemctl enable getty@tty1.service >/dev/null
systemctl restart getty@tty1.service || true
ok "getty@tty1 (auto-login) activé."

# ---------- 2) Session profil: starting UWSM -> Hyprland ----------
BLOCK_START="# >>> UWSM/Hyprland autostart (tty1) >>>"
BLOCK_END="# <<< UWSM/Hyprland autostart (tty1) <<<"
BLOCK_CONTENT=$(
  cat <<'EOS'
# >>> UWSM/Hyprland autostart (tty1) >>>
# Starting the UWSM/Hyprland session on TTY1 start,
# and only if no other graphical session are started
if uwsm check may-start; then
    exec uwsm start hyprland-uwsm.desktop
fi
# <<< UWSM/Hyprland autostart (tty1) <<<
EOS
)

add_block_idempotent() {
  local file="$1"
  # Create the file if it doesn't already exist
  [[ -f "$file" ]] || touch "$file"
  # Remove the old block if it exist, then add the new one
  if grep -qF "$BLOCK_START" "$file"; then
    awk -v start="$BLOCK_START" -v end="$BLOCK_END" '
      BEGIN{skip=0}
      index($0,start){skip=1; next}
      index($0,end){skip=0; next}
      skip==0{print}
    ' "$file" >"$file.tmp"
    mv "$file.tmp" "$file"
  fi
  printf "\n%s\n" "$BLOCK_CONTENT" >>"$file"
}

# Handle bash and zsh (we feed them both, it's safe)
BASH_PROFILE="$USER_HOME/.bash_profile"
ZSH_PROFILE="$USER_HOME/.zprofile"

add_block_idempotent "$BASH_PROFILE"
add_block_idempotent "$ZSH_PROFILE"

chown "$TARGET_USER":"$TARGET_USER" "$BASH_PROFILE" "$ZSH_PROFILE"

ok "Blocs added to: $BASH_PROFILE and $ZSH_PROFILE"
