#!/usr/bin/env bash
# Configure autologin on TTY1 and auto-start Hyprland via UWSM for a given user.
# Usage: sudo bash setup-autologin-hyprland-uwsm.sh <username>

set -euo pipefail

# ---------- helpers ----------
err() { printf "\e[31m[error]\e[0m %s\n" "$*" >&2; }
ok() { printf "\e[32m[ok]\e[0m %s\n" "$*"; }
info() { printf "\e[34m[info]\e[0m %s\n" "$*"; }

require_root() {
  if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    err "This script need to be run as root (sudo)."
    exit 1
  fi
}

check_bin() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Can't find binary: $1. Install it and re-run this script."
    exit 1
  fi
}

# ---------- inputs ----------
require_root

if [[ $# -lt 1 ]]; then
  err "User: $0 <username>"
  exit 1
fi

TARGET_USER="$1"
if ! id "$TARGET_USER" >/dev/null 2>&1; then
  err "The user '$TARGET_USER' don't exist."
  exit 1
fi

USER_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
if [[ -z "$USER_HOME" || ! -d "$USER_HOME" ]]; then
  err "Can't find the HOME folder of $TARGET_USER."
  exit 1
fi

# ---------- sanity checks ----------
check_bin agetty
check_bin uwsm
check_bin Hyprland

# ---------- 1) systemd agetty autologin ----------
info "Configuring auto-login on TTY1 for user $TARGET_USER …"

DROPIN_DIR="/etc/systemd/system/getty@tty1.service.d"
DROPIN_FILE="$DROPIN_DIR/override.conf"

mkdir -p "$DROPIN_DIR"

cat >"$DROPIN_FILE" <<EOF
# Generated by setup-autologin.sh
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin ${TARGET_USER} --noclear %I \$TERM
Type=simple
EOF

ok "Drop-in écrit: $DROPIN_FILE"

# Activer et recharger systemd
systemctl daemon-reload
systemctl enable getty@tty1.service >/dev/null
systemctl restart getty@tty1.service || true
ok "getty@tty1 (auto-login) activé."

# ---------- 2) profil de session: démarrer UWSM -> Hyprland ----------
info "Ajout du démarrage automatique UWSM/Hyprland dans le profil de session …"

BLOCK_START="# >>> UWSM/Hyprland autostart (tty1) >>>"
BLOCK_END="# <<< UWSM/Hyprland autostart (tty1) <<<"
BLOCK_CONTENT=$(
  cat <<'EOS'
# >>> UWSM/Hyprland autostart (tty1) >>>
# Démarre la session UWSM/Hyprland quand on se logue sur TTY1,
# et uniquement si aucune session graphique n'est déjà active.
if uwsm check may-start; then
    exec uwsm start hyprland-uwsm.desktop
fi
# <<< UWSM/Hyprland autostart (tty1) <<<
EOS
)

add_block_idempotent() {
  local file="$1"
  # Crée le fichier s'il n'existe pas
  [[ -f "$file" ]] || touch "$file"
  # Retire un ancien bloc si présent, puis ajoute le nouveau
  if grep -qF "$BLOCK_START" "$file"; then
    # supprimer bloc existant
    awk -v start="$BLOCK_START" -v end="$BLOCK_END" '
      BEGIN{skip=0}
      index($0,start){skip=1; next}
      index($0,end){skip=0; next}
      skip==0{print}
    ' "$file" >"$file.tmp"
    mv "$file.tmp" "$file"
  fi
  printf "\n%s\n" "$BLOCK_CONTENT" >>"$file"
}

# Gérer bash et zsh (on les alimente tous les deux, c’est sans risque)
BASH_PROFILE="$USER_HOME/.bash_profile"
ZSH_PROFILE="$USER_HOME/.zprofile"

add_block_idempotent "$BASH_PROFILE"
add_block_idempotent "$ZSH_PROFILE"

chown "$TARGET_USER":"$TARGET_USER" "$BASH_PROFILE" "$ZSH_PROFILE"

ok "Blocs added to: $BASH_PROFILE and $ZSH_PROFILE"

# ---------- 3) conseils ----------
cat <<TIP

${OK:-}
Hint:
- Au prochain boot (ou déconnexion/reconnexion), $TARGET_USER sera auto-loggé sur TTY1
  et la session se lancera via: 'uwsm start hyprland-uwsm.desktop'.
- Pour tester sans rebooter: change vers TTY1 (Ctrl+Alt+F1), déconnecte-toi, puis reconnecte-toi.

Désactivation / rollback:
- Supprime le drop-in et relance systemd:
    sudo rm -f "$DROPIN_FILE"
    sudo systemctl daemon-reload
    sudo systemctl restart getty@tty1.service
- Édite '$BASH_PROFILE' et '$ZSH_PROFILE' pour retirer le bloc entre:
    $BLOCK_START
    $BLOCK_END

TIP
