#!/usr/bin/env bash
# Configure autologin on TTY1 and auto-start Hyprland via UWSM for a given user.
# Usage: sudo bash setup-autologin-hyprland-uwsm.sh <username>

# Source utility functions
source ../utilities/utils.sh

set -euo pipefail

# Ensure root
require_root

if [[ $# -lt 1 ]]; then
  err "Usage: $0 <username>"
  exit 1
fi

TARGET_USER="$1"
if ! id "$TARGET_USER" >/dev/null 2>&1; then
  err "The user '$TARGET_USER' don't exist."
  exit 1
fi

USER_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
if [[ -z "$USER_HOME" || ! -d "$USER_HOME" ]]; then
  err "Can't find the HOME folder of $TARGET_USER."
  exit 1
fi

# ---------- sanity checks ----------
have_cmd agetty || die "agetty not found"
have_cmd uwsm || die "uwsm not found"
have_cmd Hyprland || die "Hyprland not found"

# ---------- 1) systemd agetty autologin ----------
info "Configuring auto-login on TTY1 for user $TARGET_USER …"

DROPIN_DIR="/etc/systemd/system/getty@tty1.service.d"
DROPIN_FILE="$DROPIN_DIR/override.conf"

ensure_dir "$DROPIN_DIR"

cat >"$DROPIN_FILE" <<EOF
# Generated by setup-autologin.sh
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin ${TARGET_USER} --noclear %I \$TERM
Type=simple
EOF

ok "Drop-in writen: $DROPIN_FILE"

# Activate and reload the system
systemctl daemon-reload
systemctl enable getty@tty1.service >/dev/null
systemctl restart getty@tty1.service || true
ok "getty@tty1 (auto-login) activated."

# ---------- 2) Session profil: starting UWSM -> Hyprland ----------
BLOCK_START="# >>> UWSM/Hyprland autostart (tty1) >>>"
BLOCK_END="# <<< UWSM/Hyprland autostart (tty1) <<<"
BLOCK_CONTENT=$(
  cat <<'EOS'
# >>> UWSM/Hyprland autostart (tty1) >>>
# Starting the UWSM/Hyprland session on TTY1 start,
# and only if no other graphical session are started
if uwsm check may-start; then
    exec uwsm start hyprland-uwsm.desktop
fi
# <<< UWSM/Hyprland autostart (tty1) <<<
EOS
)

# Handle bash and zsh (we feed them both, it's safe)
BASH_PROFILE="$USER_HOME/.bash_profile"
ZSH_PROFILE="$USER_HOME/.zprofile"

add_or_update_block "$BASH_PROFILE" "$BLOCK_START" "$BLOCK_END" "$BLOCK_CONTENT"
add_or_update_block "$ZSH_PROFILE" "$BLOCK_START" "$BLOCK_END" "$BLOCK_CONTENT"

chown "$TARGET_USER":"$TARGET_USER" "$BASH_PROFILE" "$ZSH_PROFILE"

ok "Blocs added to: $BASH_PROFILE and $ZSH_PROFILE"
